### ISSUE TITLE
Websocket related files are missing 

### ISSUE THREAD

**Issue by Jishang** [justinb01981/tiny-webrtc-gw#5]
Hi,

while compiling the code getting an error of missing file of the websocket related. I have posted the errors below.

gcc: error: config.c: No such file or directory
gcc: error: ws/cwebsocket/lib/*.c: No such file or directory

thanks.

**Comment by justinb01981** [comment]
Should be fixed in master now, by adding submodule to https://github.com/m8rge/cwebsocket
(must do git clone --recursive now, though)
