### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by seeme-o** [justinb01981/tiny-webrtc-gw#8]
Hi, I was wondering if you are still working on this project and if you plan on any future development? I'm thinking about using it for a node.js module because I like your coding style but I'd rather not commit my time if not going anywhere. Thanks!

**Comment by justinb01981** [comment]
Heya. Sorry I didn't see this sooner. Thanks for the interest.
I'm still supporting it, and fixing bugs as I find them.
But most of my cycles go of course to my day job so this is mostly a hobby.

**Comment by justinb01981** [comment]
Old, but if this is still uncertain, please reopen it?
