### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shrisha108** [justinb01981/tiny-webrtc-gw#9]
Got this at the end of compiling:
```
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: all] Error 1
```
I'm on Centos 8. Any dependencies?

**Comment by justinb01981** [comment]
Check out this forum post about missing static libraries on centos:
https://forums.centos.org/viewtopic.php?t=3517
You should just need to yum install some packages (like glibc-static, pthread-devel, etc).. but I've only built on ubuntu distros, so the package names aren't necessarily the same.
Googling these (pretty common) build errors should lead you in the right direction.
